### ISSUE TITLE
Can't get musejazz to work

### ISSUE THREAD

**Issue by Taxel** [cgnieder/leadsheets#14]
Hi @cgnieder, I really enjoy working with this package so far, but I am having trouble understanding how to use the musejazz font to work.

The main reason for my confusion is that the fonts at [https://github.com/musescore/](https://github.com/musescore/MuseScore/tree/master/fonts/musejazz) are separated in `musejazz.otf` and `musejazzText.otf`.

`leadsheets` apparently only loads the first one. This is why I only see the `b` and `#` characters but not the chord itself (C#m becomes #).

Is there a musejazz font which is not separated or another way how to fix this? I would appreciate being able to use that font.

Thanks in advance
Taxel

**Comment by cgnieder** [comment]
I'm not sure I can be of much help. This works on my system (compiled with either LuaLaTeX or XeLaTeX):

```latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{MuseJazz}
\usepackage{lipsum}
\begin{document}

\lipsum[1]

\end{document}
```

![grafik](https://user-images.githubusercontent.com/2248538/37976699-5dcf92a6-31e2-11e8-857a-5a5beeef2e22.png)

**Comment by Taxel** [comment]
So the way to go is not to install the fonts only but the whole application? This would be a helpful addition to the package info ;)

Will try this and confirm if it works.
Thanks!

**Comment by Taxel** [comment]
No such luck.
I am getting the following error:
`LaTeX Font Warning: Font shape 'TU/MuseJazz(0)/bx/n' undefined
(Font)              using 'TU/MuseJazz(0)/m/n' instead on input line 36.`

**Comment by Taxel** [comment]
Found a workaround, so for everyone who has this problem in the future:
You don't need to install MuseScore. What you need to do is download the font "Musejazz Text"
[HERE](https://github.com/musescore/MuseScore/tree/master/fonts/musejazz). Then install that font.
Why not "Musejazz"? Because apparently, it does not contain the normal text characters.
Then, after importing the leadsheets musejazz package, overwrite the imported font:

    \useleadsheetslibrary{musejazz} 
    \newfontfamily \musejazz {MuseJazzText}

And that's it! It should work now. If not, check if the font is properly installed, visible in e.g. Word and can be found via

    luatfload-tool --find="MuseJazzText"

If not: Google the error, it's a generic luatfload-tool error and not specific to MuseJazz Text ;)

@cgnieder This can be closed now.
