### ISSUE TITLE
Option to have bars only in chord row

### ISSUE THREAD

**Issue by EuOw** [cgnieder/leadsheets#15]
Hej,
one thing I'd like very much would be an option to have all bars automatically only in the 'chord row', i.e. not disrupting the song text flow, but only subtly indicating when two chords are played in one measure. Right now I'm trying something like 
`^-{|C} It's easy if ^{Cmaj7}you ^-{|F}try \\`
but it would be much more convenient if there was an option for this.

**Comment by cgnieder** [comment]
Can you make a complete (but small!) example? Right now I have difficulties understanding the issue.

**Comment by EuOw** [comment]
From a users perspective, I want to transform input like this
```
    In the | {D}town where {C}I was | {G}born
    {Em}Lived a | {Am}man who {C}sailed to | {D}sea.
```
to look something like this:
![grafik](https://user-images.githubusercontent.com/33802636/65816911-ac980780-e201-11e9-98fb-eb644b6d9247.png)

Thank you for considering it :)

**Comment by cgnieder** [comment]
You could maybe do something like the following?

```latex
\documentclass{article}

\usepackage{leadsheets}

\ExplSyntaxOn
\cs_new_protected:Npn \barline:
  { \leadsheets_place_above:nnn {c} {\texttt{|}} {\vphantom{K}} }
\leadsheets_define_shorthand:NN | \barline:
\ExplSyntaxOff

\begin{document}

\setleadsheets{
  bar-shortcuts ,
  song-format = \ttfamily
}

\begin{song}{title=Yellow Submarine}
\begin{verse}
  In the | ^{D}town where ^{C}I was | ^{G}born \\
  ^{Em}Lived a | ^{Am}man who ^{C}sailed to | ^{D}sea.
\end{verse}
\end{song}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/2248538/66049701-314d9300-e52c-11e9-8424-8567c3307c6b.png)
