### ISSUE TITLE
Control sequence \prop_item:Nn undefined

### ISSUE THREAD

**Issue by ntonnaett** [cgnieder/leadsheets#2]
When I compile a minimal example I get this error. But it doesn't happen when I compile the documentation of leadsheets...

**Comment by ntonnaett** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/command-not-defined"
! 
! Control sequence \prop_item:Nn undefined.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.37 ...ate_variant:Nn \prop_item:Nn        { NV }
[…]
(./leadsheets.library.songs.code.tex
(./leadsheets.library.musicsymbols.code.tex)
(./leadsheets.library.chordnames.code.tex)
(./leadsheets.library.chords.code.tex)
(./leadsheets.library.shorthands.code.tex)
(./leadsheets.library.properties.code.tex)
(./leadsheets.library.transposing.code.tex)
(./leadsheets.library.templates.code.tex)
(./leadsheets.library.translations.code.tex))) (./test.aux)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(/usr/share/texlive/texmf-dist/tex/latex/translations/translations-basic-dictionary-english.trsl)
! Undefined control sequence.
\leadsheets_get_property:nn #1#2->\prop_item:cn 
                                                {l__leadsheets_songs_#2_prop...
l.6       lyrics={traditional}, tags={srv,blues}}

Is it a bug in the translations package?

**Comment by cgnieder** [comment]
`\prop_item:Nn` has been added to expl3 on 2014-07-17, so my guess is that your TeX distribution is outdated and needs an update.
