### ISSUE TITLE
remember-chords does not work with German umlauts

### ISSUE THREAD

**Issue by JuergenMann** [cgnieder/leadsheets#20]
I have this song-snippet:
```latex
\begin{document}
\begin{song}[remember-chords]{title={Zwergentrinklied II}}
\begin{verse}
doch ^{D}heut sind wir hier ^{E}beisammen und das ^{D}Gestern ^{E}scheint so ^{A}fern.
\end{verse}
\begin{verse}
Heute ^messen wir uns nicht mit ^Äxten, sondern  ^besten^falls mit ^Bier!
\end{verse}
\end{song}
\end{document}
```

Error message:
```
! Package inputenc Error: Invalid UTF-8 byte sequence.See the inputenc package documentation for explanation.Type H <return> for immediate help.... \end{song}
```

Workaround: I set a class for the second verse and wrote the chords again in it.

**Comment by L0GL0G** [comment]
This can be easily circumvented by using the umlaut shorthand notation from the babel package, e.g. write `^"Axten`.

**Comment by cgnieder** [comment]
The old problem that pdflatex does not have a *true* unicode support. lualatex for example handles this without problem. I'd probably write

```latex
^{Äxten}
```

**Comment by JuergenMann** [comment]
Thanks @cgnieder and @L0GL0G for your answers. That helps a lot
