### ISSUE TITLE
Page breaking for long songs

### ISSUE THREAD

**Issue by Krediman** [cgnieder/leadsheets#21]
A long song will sometimes need more than one page, especially if printed on small paper formats like A5.

AFAIK leadsheets currently has no option to do a pagebreak only between verse-like environments (this means a Verse-like Environment is never broken and always on one page). I tried
`\pagebreak[3]`

This moves up to three lines according to my experiments, but that is not enough in all cases. Of course I could use `\pagebreak[4]`, but this forces me to rework the whole book after every Change. 

Another idea:

```
\nopagebreak
begin{verse}
    …
end{verse}

…
```
does nothing. AFAIK it is because of the `\itemize` environment used internally. 

For Reference see the following example.
[test.tex](https://github.com/cgnieder/leadsheets/files/5252837/test.tex.txt)
(Renamed from "test.tex")
[test.pdf](https://github.com/cgnieder/leadsheets/files/5252839/test.pdf)

This is either a request for a feature or for support, I think.

PS. Please Note that this is my first github issue. I may still have a lot to learn.

**Comment by cgnieder** [comment]
Well, you can define a template for verses which keeps them on one page, e.g., by putting them in a `minipage`:

```latex
\makeatletter
\defineversetypetemplate{minipage}{%
  \par\noindent
  \begin{minipage}{\linewidth}%
    \begin{itemize}
      \@itemdepth=0
      \ifobeylines{%
        \setlength{\parskip}{0pt}%
        \setleadsheets{ obey-lines-parskip = \parsep }%
      }{}%
      \item[{\verselabel}]%
}{%
    \end{itemize}%
  \end{minipage}%
}
\makeatother

\setleadsheets{
  verses-label-format = \bfseries ,
  verse/numbered = true ,
  verse/template = minipage ,
  chorus/template = minipage
}
```

**Comment by Krediman** [comment]
This looks pretty good to me. Sorry, for letting the Issue open for such a long time. I forgot to close the Issue.
