### ISSUE TITLE
How do I install this package

### ISSUE THREAD

**Issue by tappoz** [cgnieder/leadsheets#26]
I am trying to get my head around deep LaTeX topics - so far I've been writing "normal" stuff like maths, but I cannot figure out how to extend the standard LaTeX distribution with niche (but great!) packages like `leadsheets`.

As far as I understand the package when on CTAN (https://github.com/cgnieder/leadsheets) should be already included in the standard LaTeX distribution, but when I try to compile a document I get:

```
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>

! LaTeX Error: File `leadsheet.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
```

So I tried to figure out how to use the LaTeX package manager `tlmgr` like this: `tlmgr install leadsheet --verify-repo=none -v`, but the package is not found with the message: `tlmgr install: package leadsheet not present in repository.`

I have to use `--verify-repo=none` because for some reason Debian based Linux environments are messing with the CTAN certificates.

Is there a proper way/command/procedure of extending LaTeX functionality with `leadsheets`? How can I "install" `leadsheets`?

**Comment by tappoz** [comment]
Apologies - the moment I wrote this issue I realized I had a typo on the command, it's `leadsheets` not `leadsheet`.
This works: `tlmgr install leadsheets --verify-repo=none -v`
I swear I've been banging my head around these LaTeX topics for quite a long time, without realizing this dummy spelling mistake :man_facepalming:

**Comment by ioanlucut** [comment]
@tappoz Thanks for sharing!
