### ISSUE TITLE
Embedding `\begin{chorus}` in `\newcommand` causing chords to appear twice

### ISSUE THREAD

**Issue by schickm** [cgnieder/leadsheets#29]
Let me start off by saying I'm very new to LaTeX, so I might be doing something fundamentally flawed here.

I'd like to only specify the chorus one time, and then have it print repeatedly (chords and lyrics) in-between the verses.  Some googling pointed me towards using `\newcommand` to define a reusable command.  So, I defined my chorus inside of the it.

```latex
\documentclass{article}
\usepackage{leadsheets}
\begin{document}
\begin{song}[transpose=5,remember-chords,verse/numbered]{title={Here Comes The Sun}, band={The Beatles}, 
  key={A}}


\newcommand\mychorus
{
  \begin{chorus}
    ^{A} Here comes the sun  do doo do do \\
    ^{D} Here comes the sun, \\
    ^{B7} And I say, ^{A} It's all right \\
  \end{chorus}
}

\mychorus % This behaves as expected

\begin{verse}
  ^{A} Little darling It's been a long,^{D} cold lonely win^{E7}ter \\
  ^{A} Little darling It feels like years^{D} since it's been here^{E7} \\
\end{verse}

\mychorus % This prints the chords twice

\end{song}
\end{document}
```

The first usage of `\mychorus` behaves as I'd expect.  However, the second usage prints any `^` chords two times, one right over the other.  Interestingly, the lower one doesn't get transposed (maybe that's a clue 🤷).

![image](https://user-images.githubusercontent.com/197222/163072592-434df0ab-7517-402f-a322-821e4e8c9491.png)

Thank you for the wonderful library!  I'm really excited to get to work moving all my old lead sheets off of Google Docs and into something much more maintainable!

**Comment by cgnieder** [comment]
This is because you have set `remember-chords`.

**Comment by schickm** [comment]
That did the trick, thanks @cgnieder!
