### ISSUE TITLE
intro section is transposed when transpose option is given

### ISSUE THREAD

**Issue by chbndrhnns** [cgnieder/leadsheets#6]
To me, it looks like a section
```
\begin{intro}
^{C} ^{G} ^{C}
\end{intro}
```
is not transposed when a transpose option is given for a song.

**Comment by cgnieder** [comment]
I can't reproduce this:

```latex
\documentclass{article}

\usepackage{leadsheets}

\begin{document}

\begin{song}[transpose=3]{title=foo,key=C}
\begin{intro}
  ^{C} ^{G} ^{C}
\end{intro}
\end{song}

\end{document}
```

![leadsheets](https://cloud.githubusercontent.com/assets/2248538/8646407/fcf394c0-294f-11e5-9eda-187583af126d.png)

**Comment by chbndrhnns** [comment]
Yeah, you are right. I actually omitted the "^" characters to have the chords in the same line as the "intro" tag because there is no text in the intro, only chords. Is there any other way to achieve this?

**Comment by cgnieder** [comment]
Yes: use `\writechord{C}` or the shortcut `_{C}`.

**Comment by chbndrhnns** [comment]
Great! Thank you! I am just adopting your great package for my song library!
